In [1]:
import pandas as pd

In [4]:
sk=pd.read_csv("C:/Users/RANJITH BABU/Downloads/index 1.csv")

In [5]:
sk.head()

         date datetime cash_type                 card  money    coffee_name
0  01-03-2024  15:50.5      card  ANON-0000-0000-0001   38.7          Latte
1  01-03-2024  19:22.5      card  ANON-0000-0000-0002   38.7  Hot Chocolate
2  01-03-2024  20:18.1      card  ANON-0000-0000-0002   38.7  Hot Chocolate
3  01-03-2024  46:33.0      card  ANON-0000-0000-0003   28.9      Americano
4  01-03-2024  48:14.6      card  ANON-0000-0000-0004   38.7          Latte

In [6]:
sk.loc[0]

date                    01-03-2024
datetime                   15:50.5
cash_type                     card
card           ANON-0000-0000-0001
money                         38.7
coffee_name                  Latte
Name: 0, dtype: object

In [7]:
sk.loc[0:19]

,date,datetime,cash_type,card,money,coffee_name
0,01-03-2024,15:50.5,card,ANON-0000-0000-0001,38.7,Latte
1,01-03-2024,19:22.5,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,01-03-2024,20:18.1,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,01-03-2024,46:33.0,card,ANON-0000-0000-0003,28.9,Americano
4,01-03-2024,48:14.6,card,ANON-0000-0000-0004,38.7,Latte
5,01-03-2024,39:47.7,card,ANON-0000-0000-0005,33.8,Americano with Milk
6,01-03-2024,19:02.8,card,ANON-0000-0000-0006,38.7,Hot Chocolate
7,01-03-2024,39:03.6,card,ANON-0000-0000-0007,33.8,Americano with Milk
8,01-03-2024,22:01.8,card,ANON-0000-0000-0008,38.7,Cocoa
9,01-03-2024,23:15.9,card,ANON-0000-0000-0008,33.8,Americano with Milk
10,01-03-2024,29:17.4,card,ANON-0000-0000-0009,33.8,Americano with Milk
11,02-03-2024,22:07.0,card,ANON-0000-0000-0010,28.9,Americano
12,02-03-2024,30:35.7,cash,NaN,40.0,Latte
13,02-03-2024,41:41.2,card,ANON-0000-0000-0011,33.8,Americano with Milk
14,02-03-2024,59:45.5,card,ANON-0000-0000-0012,33.8,Americano with Milk
15,02-03-2024,38:35.5,card,ANON-0000-0000-0013,28.9,Americano
16,02-03-2024,37:24.5,card,ANON-0000-0000-0014,33.8,Americano with Milk
17,02-03-2024,34:55.0,card,ANON-0000-0000-0004,28.9,Americano
18,03-03-2024,10:44.0,cash,NaN,40.0,Latte
19,03-03-2024,27:18.6,card,ANON-0000-0000-0015,38.7,Latte

In [8]:
sk.iloc[0:10,0:5]

         date datetime cash_type                 card  money
0  01-03-2024  15:50.5      card  ANON-0000-0000-0001   38.7
1  01-03-2024  19:22.5      card  ANON-0000-0000-0002   38.7
2  01-03-2024  20:18.1      card  ANON-0000-0000-0002   38.7
3  01-03-2024  46:33.0      card  ANON-0000-0000-0003   28.9
4  01-03-2024  48:14.6      card  ANON-0000-0000-0004   38.7
5  01-03-2024  39:47.7      card  ANON-0000-0000-0005   33.8
6  01-03-2024  19:02.8      card  ANON-0000-0000-0006   38.7
7  01-03-2024  39:03.6      card  ANON-0000-0000-0007   33.8
8  01-03-2024  22:01.8      card  ANON-0000-0000-0008   38.7
9  01-03-2024  23:15.9      card  ANON-0000-0000-0008   33.8

In [9]:
sk[sk["money"]>30]

,date,datetime,cash_type,card,money,coffee_name
0,01-03-2024,15:50.5,card,ANON-0000-0000-0001,38.70,Latte
1,01-03-2024,19:22.5,card,ANON-0000-0000-0002,38.70,Hot Chocolate
2,01-03-2024,20:18.1,card,ANON-0000-0000-0002,38.70,Hot Chocolate
4,01-03-2024,48:14.6,card,ANON-0000-0000-0004,38.70,Latte
5,01-03-2024,39:47.7,card,ANON-0000-0000-0005,33.80,Americano with Milk
...,...,...,...,...,...,...
3630,23-03-2025,07:11.3,card,ANON-0000-0000-1196,35.76,Latte
3631,23-03-2025,34:54.9,card,ANON-0000-0000-1158,35.76,Cappuccino
3632,23-03-2025,43:37.4,card,ANON-0000-0000-1315,35.76,Cocoa
3633,23-03-2025,44:16.9,card,ANON-0000-0000-1315,35.76,Cocoa
3635,23-03-2025,11:38.6,card,ANON-0000-0000-1275,35.76,Latte

In [10]:
sk[sk["money"]<30]

            date datetime cash_type                 card  money coffee_name
3     01-03-2024  46:33.0      card  ANON-0000-0000-0003  28.90   Americano
11    02-03-2024  22:07.0      card  ANON-0000-0000-0010  28.90   Americano
15    02-03-2024  38:35.5      card  ANON-0000-0000-0013  28.90   Americano
17    02-03-2024  34:55.0      card  ANON-0000-0000-0004  28.90   Americano
20    03-03-2024  33:56.1      card  ANON-0000-0000-0016  28.90     Cortado
...          ...      ...       ...                  ...    ...         ...
3617  21-03-2025  59:24.3      card  ANON-0000-0000-1170  25.96   Americano
3623  22-03-2025  25:59.7      card  ANON-0000-0000-1306  25.96   Americano
3624  22-03-2025  06:21.6      card  ANON-0000-0000-1309  25.96   Americano
3626  22-03-2025  57:58.2      card  ANON-0000-0000-1302  21.06    Espresso
3634  23-03-2025  47:28.7      card  ANON-0000-0000-1316  25.96   Americano

[1215 rows x 6 columns]

In [11]:
df[df["money"] >= 30]

,date,datetime,cash_type,card,money,coffee_name
0,01-03-2024,15:50.5,card,ANON-0000-0000-0001,38.70,Latte
1,01-03-2024,19:22.5,card,ANON-0000-0000-0002,38.70,Hot Chocolate
2,01-03-2024,20:18.1,card,ANON-0000-0000-0002,38.70,Hot Chocolate
4,01-03-2024,48:14.6,card,ANON-0000-0000-0004,38.70,Latte
5,01-03-2024,39:47.7,card,ANON-0000-0000-0005,33.80,Americano with Milk
...,...,...,...,...,...,...
3630,23-03-2025,07:11.3,card,ANON-0000-0000-1196,35.76,Latte
3631,23-03-2025,34:54.9,card,ANON-0000-0000-1158,35.76,Cappuccino
3632,23-03-2025,43:37.4,card,ANON-0000-0000-1315,35.76,Cocoa
3633,23-03-2025,44:16.9,card,ANON-0000-0000-1315,35.76,Cocoa
3635,23-03-2025,11:38.6,card,ANON-0000-0000-1275,35.76,Latte

In [12]:
df[df["money"] <= 30]

            date datetime cash_type                 card  money coffee_name
3     01-03-2024  46:33.0      card  ANON-0000-0000-0003  28.90   Americano
11    02-03-2024  22:07.0      card  ANON-0000-0000-0010  28.90   Americano
15    02-03-2024  38:35.5      card  ANON-0000-0000-0013  28.90   Americano
17    02-03-2024  34:55.0      card  ANON-0000-0000-0004  28.90   Americano
20    03-03-2024  33:56.1      card  ANON-0000-0000-0016  28.90     Cortado
...          ...      ...       ...                  ...    ...         ...
3617  21-03-2025  59:24.3      card  ANON-0000-0000-1170  25.96   Americano
3623  22-03-2025  25:59.7      card  ANON-0000-0000-1306  25.96   Americano
3624  22-03-2025  06:21.6      card  ANON-0000-0000-1309  25.96   Americano
3626  22-03-2025  57:58.2      card  ANON-0000-0000-1302  21.06    Espresso
3634  23-03-2025  47:28.7      card  ANON-0000-0000-1316  25.96   Americano

[1226 rows x 6 columns]

In [13]:
df[(df["money"] > 30) & (df["money"] < 50)]

,date,datetime,cash_type,card,money,coffee_name
0,01-03-2024,15:50.5,card,ANON-0000-0000-0001,38.70,Latte
1,01-03-2024,19:22.5,card,ANON-0000-0000-0002,38.70,Hot Chocolate
2,01-03-2024,20:18.1,card,ANON-0000-0000-0002,38.70,Hot Chocolate
4,01-03-2024,48:14.6,card,ANON-0000-0000-0004,38.70,Latte
5,01-03-2024,39:47.7,card,ANON-0000-0000-0005,33.80,Americano with Milk
...,...,...,...,...,...,...
3630,23-03-2025,07:11.3,card,ANON-0000-0000-1196,35.76,Latte
3631,23-03-2025,34:54.9,card,ANON-0000-0000-1158,35.76,Cappuccino
3632,23-03-2025,43:37.4,card,ANON-0000-0000-1315,35.76,Cocoa
3633,23-03-2025,44:16.9,card,ANON-0000-0000-1315,35.76,Cocoa
3635,23-03-2025,11:38.6,card,ANON-0000-0000-1275,35.76,Latte

In [14]:
df[(df["money"] < 30) | (df["money"] > 50)]

            date datetime cash_type                 card  money coffee_name
3     01-03-2024  46:33.0      card  ANON-0000-0000-0003  28.90   Americano
11    02-03-2024  22:07.0      card  ANON-0000-0000-0010  28.90   Americano
15    02-03-2024  38:35.5      card  ANON-0000-0000-0013  28.90   Americano
17    02-03-2024  34:55.0      card  ANON-0000-0000-0004  28.90   Americano
20    03-03-2024  33:56.1      card  ANON-0000-0000-0016  28.90     Cortado
...          ...      ...       ...                  ...    ...         ...
3617  21-03-2025  59:24.3      card  ANON-0000-0000-1170  25.96   Americano
3623  22-03-2025  25:59.7      card  ANON-0000-0000-1306  25.96   Americano
3624  22-03-2025  06:21.6      card  ANON-0000-0000-1309  25.96   Americano
3626  22-03-2025  57:58.2      card  ANON-0000-0000-1302  21.06    Espresso
3634  23-03-2025  47:28.7      card  ANON-0000-0000-1316  25.96   Americano

[1215 rows x 6 columns]

In [15]:
df[~(df["money"] > 30)]

            date datetime cash_type                 card  money coffee_name
3     01-03-2024  46:33.0      card  ANON-0000-0000-0003  28.90   Americano
11    02-03-2024  22:07.0      card  ANON-0000-0000-0010  28.90   Americano
15    02-03-2024  38:35.5      card  ANON-0000-0000-0013  28.90   Americano
17    02-03-2024  34:55.0      card  ANON-0000-0000-0004  28.90   Americano
20    03-03-2024  33:56.1      card  ANON-0000-0000-0016  28.90     Cortado
...          ...      ...       ...                  ...    ...         ...
3617  21-03-2025  59:24.3      card  ANON-0000-0000-1170  25.96   Americano
3623  22-03-2025  25:59.7      card  ANON-0000-0000-1306  25.96   Americano
3624  22-03-2025  06:21.6      card  ANON-0000-0000-1309  25.96   Americano
3626  22-03-2025  57:58.2      card  ANON-0000-0000-1302  21.06    Espresso
3634  23-03-2025  47:28.7      card  ANON-0000-0000-1316  25.96   Americano

[1226 rows x 6 columns]

In [16]:
df.sort_values("money", ascending=True)

            date datetime cash_type                 card  money    coffee_name
977   18-07-2024  11:23.4      card  ANON-0000-0000-0381  18.12       Espresso
1512  09-09-2024  06:59.7      card  ANON-0000-0000-0603  18.12       Espresso
1537  12-09-2024  57:25.6      card  ANON-0000-0000-0347  18.12       Espresso
1557  15-09-2024  42:40.9      card  ANON-0000-0000-0347  18.12       Espresso
1490  07-09-2024  20:59.3      card  ANON-0000-0000-0012  18.12       Espresso
...          ...      ...       ...                  ...    ...            ...
105   14-03-2024  02:12.2      cash                  NaN  40.00          Latte
82    11-03-2024  24:15.0      cash                  NaN  40.00     Cappuccino
18    03-03-2024  10:44.0      cash                  NaN  40.00          Latte
49    07-03-2024  25:44.0      cash                  NaN  40.00          Latte
60    09-03-2024  49:37.3      cash                  NaN  40.00  Hot Chocolate

[3636 rows x 6 columns]

In [17]:
df.sort_values("money", ascending=False)

            date datetime cash_type                 card  money coffee_name
46    07-03-2024  08:58.9      cash                  NaN  40.00       Latte
232   05-04-2024  30:50.4      cash                  NaN  40.00       Latte
233   05-04-2024  54:15.8      cash                  NaN  40.00  Cappuccino
235   05-04-2024  17:44.0      cash                  NaN  40.00       Cocoa
89    12-03-2024  15:00.3      cash                  NaN  40.00       Latte
...          ...      ...       ...                  ...    ...         ...
1271  14-08-2024  39:07.9      card  ANON-0000-0000-0095  18.12    Espresso
1193  07-08-2024  11:16.2      card  ANON-0000-0000-0469  18.12    Espresso
1200  08-08-2024  46:36.2      card  ANON-0000-0000-0141  18.12    Espresso
1581  17-09-2024  38:33.8      card  ANON-0000-0000-0628  18.12    Espresso
1027  24-07-2024  45:49.8      card  ANON-0000-0000-0012  18.12    Espresso

[3636 rows x 6 columns]

In [18]:
df.sort_values(["coffee_name", "money"], ascending=[True, False])

            date datetime cash_type                 card  money coffee_name
74    10-03-2024  44:18.5      cash                  NaN  30.00   Americano
84    11-03-2024  26:44.2      cash                  NaN  30.00   Americano
147   21-03-2024  21:01.5      cash                  NaN  30.00   Americano
205   31-03-2024  36:45.0      cash                  NaN  30.00   Americano
234   05-04-2024  55:30.9      cash                  NaN  30.00   Americano
...          ...      ...       ...                  ...    ...         ...
1692  26-09-2024  48:01.4      card  ANON-0000-0000-0671  32.82       Latte
1693  26-09-2024  21:55.7      card  ANON-0000-0000-0672  32.82       Latte
1694  26-09-2024  45:15.1      card  ANON-0000-0000-0673  32.82       Latte
1706  27-09-2024  07:43.7      card  ANON-0000-0000-0678  32.82       Latte
1707  27-09-2024  08:58.2      card  ANON-0000-0000-0678  32.82       Latte

[3636 rows x 6 columns]

In [19]:
df["double_money"] = df["money"] * 2

df.head()

,date,datetime,cash_type,card,money,coffee_name,double_money
0,01-03-2024,15:50.5,card,ANON-0000-0000-0001,38.7,Latte,77.4
1,01-03-2024,19:22.5,card,ANON-0000-0000-0002,38.7,Hot Chocolate,77.4
2,01-03-2024,20:18.1,card,ANON-0000-0000-0002,38.7,Hot Chocolate,77.4
3,01-03-2024,46:33.0,card,ANON-0000-0000-0003,28.9,Americano,57.8
4,01-03-2024,48:14.6,card,ANON-0000-0000-0004,38.7,Latte,77.4

In [20]:
df["extra_money"] = df["money"] + 10

df.head()

,date,datetime,cash_type,card,money,coffee_name,double_money,extra_money
0,01-03-2024,15:50.5,card,ANON-0000-0000-0001,38.7,Latte,77.4,48.7
1,01-03-2024,19:22.5,card,ANON-0000-0000-0002,38.7,Hot Chocolate,77.4,48.7
2,01-03-2024,20:18.1,card,ANON-0000-0000-0002,38.7,Hot Chocolate,77.4,48.7
3,01-03-2024,46:33.0,card,ANON-0000-0000-0003,28.9,Americano,57.8,38.9
4,01-03-2024,48:14.6,card,ANON-0000-0000-0004,38.7,Latte,77.4,48.7

In [21]:
df.groupby("coffee_name")["money"].min()

coffee_name
Americano              23.02
Americano with Milk    27.92
Cappuccino             32.82
Cocoa                  32.82
Cortado                23.02
Espresso               18.12
Hot Chocolate          32.82
Latte                  32.82
Name: money, dtype: float64

In [22]:
df.groupby("coffee_name")["money"].max()

coffee_name
Americano              30.0
Americano with Milk    35.0
Cappuccino             40.0
Cocoa                  40.0
Cortado                30.0
Espresso               25.0
Hot Chocolate          40.0
Latte                  40.0
Name: money, dtype: float64

In [23]:
df.groupby("coffee_name")["money"].sum()

coffee_name
Americano              15062.26
Americano with Milk    25269.12
Cappuccino             18034.14
Cocoa                   8678.16
Cortado                 7534.86
Espresso                2814.28
Hot Chocolate          10172.46
Latte                  27866.30
Name: money, dtype: float64

In [24]:
df.groupby("coffee_name")["money"].mean()

coffee_name
Americano              26.059273
Americano with Milk    30.666408
Cappuccino             35.996287
Cocoa                  35.712593
Cortado                25.804315
Espresso               21.002090
Hot Chocolate          36.072553
Latte                  35.634655
Name: money, dtype: float64

In [25]:
df.groupby("coffee_name")["money"].count()

coffee_name
Americano              578
Americano with Milk    824
Cappuccino             501
Cocoa                  243
Cortado                292
Espresso               134
Hot Chocolate          282
Latte                  782
Name: money, dtype: int64

In [26]:
df.groupby("coffee_name")["money"].std()

coffee_name
Americano              1.740508
Americano with Milk    1.940697
Cappuccino             1.906202
Cocoa                  1.307759
Cortado                2.148458
Espresso               2.078350
Hot Chocolate          1.527680
Latte                  1.936673
Name: money, dtype: float64

In [29]:
df.groupby("coffee_name")["money"].agg([
    "min",
    "max",
    "sum",
    "mean",
    "count",
    "std"
])

                       min   max       sum       mean  count       std
coffee_name
Americano            23.02  30.0  15062.26  26.059273    578  1.740508
Americano with Milk  27.92  35.0  25269.12  30.666408    824  1.940697
Cappuccino           32.82  40.0  18034.14  35.996287    501  1.906202
Cocoa                32.82  40.0   8678.16  35.712593    243  1.307759
Cortado              23.02  30.0   7534.86  25.804315    292  2.148458
Espresso             18.12  25.0   2814.28  21.002090    134  2.078350
Hot Chocolate        32.82  40.0  10172.46  36.072553    282  1.527680
Latte                32.82  40.0  27866.30  35.634655    782  1.936673